Add ForceUDPEncaps to submarinerconfig
stolostron/submariner-addon pull request #1446
Opened 2024-06-14 08:32 UTC by vthapar

Add ForceUDPEncaps field to SubmarinerConfig

2024-06-14 11:19 UTC, vthapar commented
/cc @skitt @tpantelis

2024-06-14 11:51 UTC, tpantelis requested changes

2024-06-14 11:51 UTC, tpantelis commented on pkg/apis/submarinerconfig/v1alpha1/types.go
> +	ForceUDPEncaps bool `json:"ForceUDPEncaps,omitempty"`
```suggestion
	ForceUDPEncaps bool `json:"forceUDPEncaps,omitempty"`
```

2024-06-17 12:46 UTC, yboaron commented
Overall code lgtm, and I guess we should be fine with upgrading ACM/Submariner too b/c ForceUDPEncaps defaults to false.


ForceUDPEncaps is relevant only if clusters are reachable via private IPs and ESP traffic is blocked on firewall, so I wonder how we should expose this capability to users. I don't think we need to expose this in the ACM UI.


In addition, I performed fufu test on KIND where ForceUDPEncaps was only defined on single cluster and tunnel was in error state, which probably means that ForceUDPEncaps needs to be defined in all the clusters in clusterset.

2024-06-18 17:57 UTC, tpantelis commented
/approve

2024-06-19 09:00 UTC, yboaron commented
/approve

2024-06-20 08:08 UTC, vthapar commented
/lgtm

2024-06-20 12:02 UTC, merged

2024-06-24 03:11 UTC, vthapar commented
/cherrypick release-2.10