Support multiple gateways in manifestwork deployer
stolostron/submariner-addon pull request #409
Opened 2022-06-29 06:24 UTC by mkolesnik

Current implementation always overrides the existing ManifestWork even
if the requested MachineSet is different (as is the case for multiple
gateways).

In order to properly support multiple gateways, update the existing
ManifestWork only when its necessary to add a new MachineSet.

Fixes: https://github.com/stolostron/backlog/issues/23530
Fixes: https://github.com/stolostron/backlog/issues/23007

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-06-29 07:05 UTC, mkolesnik commented
/assign @tpantelis @dfarrell07 @skitt

2022-06-29 11:35 UTC, skitt requested changes

2022-06-29 11:36 UTC, skitt commented
/cc @dfarrell07 @sridhargaddam @tpantelis

2022-06-29 11:36 UTC, skitt commented
/unassign @dfarrell07 @tpantelis

2022-06-30 12:38 UTC, mkolesnik commented on pkg/cloud/manifestwork/machineset.go
> +				"MachineSet %s already exists in ManifestWork %s", machineSet.GetName(), existingManifestWork.Name)
Yes I was using it more as a log but you suggestion makes total sense, will push a fix promptly

2022-07-07 08:19 UTC, sridhargaddam commented
/lgtm
/approve

2022-07-07 08:31 UTC, merged